version: '3.8'

services:
  postgresql:
    image: postgres:16.2
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped

  nginx:
    image: nginx:1.25.4
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  fluentbit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluentbit
    restart: unless-stopped
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

volumes:
  postgresql_data:
